baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "あがきながら覚えるTeX"
theme = "hugo-frais"
languageCode = "ja"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
preserveTaxonomyNames = true
publishDir = "docs"
canonifyURLs = true

[params]
    author = "白屋書房"
    pseudo = "isari"
    description = "ド素人が魔のシステムTeXで小説を組めるようになるまでのポンコツ入門"
    twitter = "isaribi_saitoh"
    github = "hakuoku"
    blog = "http://hakuoku.hatenablog.com/"
    disqusShortname = "hakuoku"
    headline = "TeX"
    custom_css = ["css/prism.css", "css/drawer.css"]
[taxonomies]
    tag = "tags"
    category = "categories"
    topic = "topics"

[[menu.toc]]
    name = "前説"
    identifier = "preface"
    weight = 100
[[menu.toc]]
    name = "導入"
    identifier = "setup"
    weight = 200
[[menu.toc]]
    name = "ファイル作成"
    identifier = "generate"
    weight = 300
[[menu.toc]]
    name = "本文の編集―基盤編"
    identifier = "edit"
    weight = 400
    [[menu.toc]]
        name = "全角・半角 --文字と記号の縦横"
        identifier = "tateyoko"
        weight = 430
        parent = "edit"
    [[menu.toc]]
        name = "約物"
        identifier = "punctuation"
        weight = 440
        parent = "edit"

[[menu.toc]]
    name = "索引"
    URL = "/topics/"
    identifier = "topics"
    weight = 1000
